spring:
  cassandra:
    keyspace-name: employee_db
    contact-points: 172.17.0.3
    port: 9042
    username: scylladb
    password: password
    local-datacenter: datacenter1

management:
  health:
    cassandra:
      enabled: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /salary-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /salary-api-docs
  show-actuator: true
